import {test,expect} from '@playwright/test'
test('E2E testing',async({page})=>{
    await page.goto('https://www.saucedemo.com/')
    const uname=page.locator("//input[@id='user-name']")
    await uname.fill("standard_user")
    const pwd=page.locator("//input[@id='password']")
    await pwd.fill("secret_sauce")
    const clickB=page.locator("//input[@id='login-button']")
    await clickB.click()
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html')
    const addcart=page.locator('#add-to-cart-sauce-labs-backpack')
    await addcart.click()
    const cart=page.locator("//a[@class='shopping_cart_link']")
    await cart.click()
    const checkout=page.locator('#checkout')
    checkout.click()
    const fname=page.locator("//input[@id='first-name']")
    await fname.fill("anusha")
    const lname=page.locator("//input[@id='last-name']")
    await lname.fill("mohan")
    const pcode=page.locator("//input[@id='postal-code']")
    await pcode.fill('685585')
    const cont=page.locator("//input[@id='continue']")
    await cont.click()
    const finish=page.locator("//button[@id='finish']")
    await finish.click()
    //await expect(page).toHaveURL('https://www.saucedemo.com/checkout-complete.html')
    await expect(page.locator('.complete-header')).toHaveText('Thank you for your order!')
})